spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alaska_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/alaska_db
    user: postgres
    password: postgres

mailtrap:
  sender: freyr.no-reply@outlook.com
  username: freyr.no-reply@outlook.com
  password: teste123mail-
  host: smtp-mail.outlook.com
  port: 587

url:
  activation-email: http://localhost:8080/v1/users/confirmation?token=

security:
  jwt:
    secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
    expiration: 86400000

server:
  port: 8080