name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Alaska Jar
        run: mvn clean package -DskipTests

      - name: Docker Compose Build
        working-directory: ./
        run: docker-compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/alaska:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/alaska:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/alaska:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/alaska:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/alaska:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/alaska:latest
